<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" />
        <link rel="stylesheet" href="assets/css/main.css" />
        <title>PHP REST RPG</title>
    </head>
    <body>

        <div class="container-fluid">
            <div class="row">
                <div class="col1">
                    <nav class="p-3 bg-dark text-white menu">
                        <span class="brand">RPG</span>
                        <button type="button" class="btn btn-sm mt-5">Novo Jogo</button>
                        <audio id="player" loop>
                            <source src="assets/sounds/bg.mp3" type="audio/mpeg" />
                            Seu navegador não suporta áudio tag.
                        </audio>
                        <a class="mt-5 btn btn-link sound">
                            <i class='fa fa-volume-up fa-2x'></i>
                        </a>
                    </nav>
                </div>
                <div class="col">
                    <div class="canvas">
                        <section class="frame" id="characters">
                            <h3 class="text-center text-light">Escolha um personagem</h3>
                            <div class="row text-center">
                                <div class="col">
                                    <a class="btn btn-link" onclick="characterChoice('Human');">
                                        <img src="assets/img/human_g.png" onmouseover="playSomMenu()" class="img-fluid" />
                                    </a>
                                </div>
                                <div class="col">
                                    <a class="btn btn-link" onclick="characterChoice('Orc');">
                                        <img src="assets/img/orc_g.png" onmouseover="playSomMenu()" class="img-fluid" />
                                    </a>
                                </div>
                            </div>
                        </section>
                        <section class="frame mt-5" id="game">
                            <div class="msg text-center text-light">Para iniciar clique em "Começar".</div>
                            <div class="row text-center">
                                <div class="col-2 mt-5">
                                    <nav id="menuHuman" class="menuCharacter">
                                        <div class="progress">
                                            <label>HP</label>
                                            <div id="progressHuman" class="progress-bar bg-warning" role="progressbar" aria-valuenow="<?php echo $human->hp; ?>" aria-valuemin="0" style="width: 100%" aria-valuemax="<?php echo $human->hp; ?>">
                                            </div>
                                        </div>
                                        <ul class="list-attributes">
                                            <li>
                                                <span class="title">Arma</span>
                                                <span class="content"><img src="assets/img/<?php echo $human->weapon; ?>" /></span>
                                            </li>
                                            <li>
                                                <span class="title">Ataque</span>
                                                <span class="content"><?php echo $human->attack; ?></span>
                                            </li>
                                            <li>
                                                <span class="title">Defesa</span>
                                                <span class="content"><?php echo $human->defense; ?></span>
                                            </li>
                                            <li>
                                                <span class="title">Força</span>
                                                <span class="content"><?php echo $human->strength; ?></span>
                                            </li>
                                            <li>
                                                <span class="title">Agilidade</span>
                                                <span class="content"><?php echo $human->agility; ?></span>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="col-3 mt-5">
                                    <div id="numberDiceHuman"></div>
                                    <input id="inputNumberDiceHuman" type="hidden" />
                                    <input id="inputAtkDefHuman" type="hidden" />
                                    <img src="assets/img/human_p.png" class="img-fluid" />
                                    <div class="msgHuman bg-light text-center"></div>
                                </div>
                                <div class="col-2">
                                    <input id="atacante" type="hidden" />
                                </div>
                                <div class="col-3 mt-5">
                                    <div id="numberDiceOrc"></div>
                                    <input id="inputNumberDiceOrc" type="hidden" />
                                    <input id="inputAtkDefOrc" type="hidden" />
                                    <img src="assets/img/orc_p.png" class="img-fluid" />
                                    <div class="msgOrc bg-light text-center"></div>
                                </div>
                                <div class="col-2 mt-5">
                                    <nav id="menuOrc" class="menuCharacter">
                                        <div class="progress">
                                            <label>HP</label>
                                            <div id="progressOrc" class="progress-bar bg-warning" role="progressbar" aria-valuenow="<?php echo $orc->hp; ?>" aria-valuemin="0" style="width: 100%" aria-valuemax="<?php echo $orc->hp; ?>">
                                            </div>
                                        </div>
                                        <ul class="list-attributes">
                                            <li>
                                                <span class="title">Arma</span>
                                                <span class="content"><img src="assets/img/<?php echo $orc->weapon; ?>" /></span>
                                            </li>
                                            <li>
                                                <span class="title">Ataque</span>
                                                <span class="content"><?php echo $orc->attack; ?></span>
                                            </li>
                                            <li>
                                                <span class="title">Defesa</span>
                                                <span class="content"><?php echo $orc->defense; ?></span>
                                            </li>
                                            <li>
                                                <span class="title">Força</span>
                                                <span class="content"><?php echo $orc->strength; ?></span>
                                            </li>
                                            <li>
                                                <span class="title">Agilidade</span>
                                                <span class="content"><?php echo $orc->agility; ?></span>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="row dices text-light text-center">
                                <div class="col"></div>
                                <div class="col-2">
                                    <label>Dado</label>
                                    <span class="dice battle"></span><br />
                                    <a class="btn btn-sm btn-light text-body" id="battledice" data-dice="" onclick="start(this)">Começar</a>
                                </div>
                                <div class="col"></div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>

        <!-- modals -->
        <div class="modal fade" tabindex="-1" role="dialog"  id="sound" aria-labelledby="sound" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Som</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Deseja habilitar o som?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                        <button type="button" class="btn btn-primary sound" data-dismiss="modal">Sim</button>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script src="assets/js/main.js"></script>
    </body>
</html>