<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" />
        <link rel="stylesheet" href="assets/css/main.css" />
        <title>PHP REST RPG</title>
    </head>
    <body>

        <div class="container-fluid">
            <div class="row">
                <div class="col1">
                    <nav class="p-3 bg-dark text-white menu">
                        <span class="brand">RPG</span>
                        <button type="button" class="btn btn-sm mt-5">Novo Jogo</button>
                        <audio id="player" loop>
                            <source src="assets/sounds/bg.mp3" type="audio/mpeg" />
                            Seu navegador não suporta áudio tag.
                        </audio>
                        <a class="mt-5 btn btn-link sound">
                            <i class='fa fa-volume-up fa-2x'></i>
                        </a>
                    </nav>
                </div>
                <div class="col">
                    <div class="canvas">
                        <section class="frame" id="characters">
                            <h3 class="text-center text-light">Escolha um personagem</h3>
                            <div class="row text-center">
                                <div class="col">
                                    <a class="btn btn-link" onclick="characterChoice('Human');">
                                        <img src="assets/img/human_g.png" onmouseover="playSomMenu()" class="img-fluid" />
                                    </a>
                                </div>
                                <div class="col">
                                    <a class="btn btn-link" onclick="characterChoice('Orc');">
                                        <img src="assets/img/orc_g.png" onmouseover="playSomMenu()" class="img-fluid" />
                                    </a>
                                </div>
                            </div>
                        </section>
                        <section class="frame mt-5" id="game">
                            <div class="row text-center">
                                <div class="col-2 mt-5">
                                    <nav id="menuHuman" class="menuCharacter mt-5">
                                        <a class="btn btn-sm btn-danger btn-block" onclick="attack('human')">Atacar</a>
                                        <a class="btn btn-sm btn-warning btn-block" onclick="defend('human')">Defender</a>
                                    </nav>
                                </div>
                                <div class="col-3 mt-5">
                                    <img src="assets/img/human_p.png" class="img-fluid" />
                                </div>
                                <div class="col-2"></div>
                                <div class="col-3 mt-5">
                                    <img src="assets/img/orc_p.png" class="img-fluid" />
                                </div>
                                <div class="col-2 mt-5">
                                    <nav id="menuOrc" class="menuCharacter mt-5">
                                        <a class="btn btn-sm btn-danger btn-block" onclick="attack('orc')">Atacar</a>
                                        <a class="btn btn-sm btn-warning btn-block" onclick="defend('orc')">Defender</a>
                                    </nav>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>

        <!-- modals -->
        <div class="modal fade" tabindex="-1" role="dialog"  id="sound" aria-labelledby="sound" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Som</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Deseja habilitar o som?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                        <button type="button" class="btn btn-primary sound" data-dismiss="modal">Sim</button>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script src="assets/js/main.js"></script>
    </body>
</html>